# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :osx, '10.10'

target 'SoqlXplorer' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod 'macOSThemeKit', '~> 1.2.0'
  # Pods for SoqlXplorer

  pod 'ZKSforce', '~> 40.0.0'
end
